# Generated by Django 5.0.2 on 2024-03-11 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0004_alter_skills_name'),
        ('job', '0004_jobskill'),
        ('orgranisation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('pitch', models.TextField()),
                ('score', models.FloatField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.userprofile')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.job')),
                ('organistaion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgranisation.organisations')),
            ],
        ),
    ]
