# Generated by Django 5.0.2 on 2024-03-11 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral_request', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralrequest',
            name='score',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
