# Generated by Django 5.0.2 on 2024-03-11 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referral_request', '0002_alter_referralrequest_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referralrequest',
            old_name='organistaion',
            new_name='organisation',
        ),
    ]
