# Generated by Django 5.0.2 on 2024-03-29 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral_request', '0003_rename_organistaion_referralrequest_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralrequest',
            name='status',
            field=models.CharField(blank=True, choices=[('send', 'send'), ('received', 'received'), ('approved', 'approved'), ('rejected', 'rejected')], default='send', max_length=10, null=True),
        ),
    ]
