# Generated by Django 5.0.2 on 2024-03-03 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orgranisation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('post_date', models.DateField()),
                ('title', models.CharField(max_length=150)),
                ('link', models.TextField()),
                ('employment_type', models.CharField(choices=[('Full Time', 'Full Time'), ('Internship', 'Internship'), ('Contract', 'Contract')], max_length=50)),
                ('Discipline', models.CharField(choices=[('Software Engineering', 'Software Engineering')], max_length=150)),
                ('description', models.TextField()),
                ('qualifications', models.TextField()),
                ('requirements', models.TextField()),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgranisation.organisations')),
            ],
        ),
    ]
