# Generated by Django 5.0.2 on 2024-03-09 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_skills_name'),
        ('job', '0003_job_job_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.job')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.skills')),
            ],
        ),
    ]
